[package]
name = "quordle"
authors = ["Jeb Bearer <jeb.bearer@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0"
clap = { version = "3.2", features = ["derive"] }
itertools = "0.10"
rand = "0.8"
rayon = "1.5"
